language: node_js

node_js:
  - "6"
  - "8"

sudo: false

branches:
  only:
    - master

script:
  - npm run lint:fix
  - npm run test:cov

cache:
  yarn: true
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run codecov

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: change
    on_success: change
